### PR TITLE
feat: load dark style

### PR DESCRIPTION
**Pull request by btea**
Once https://github.com/vuejs/repl/pull/200 is released, we can apply dark mode styles to the preview.

### CODE REVIEW

**Comment by btea** [comment]
@sxzz Please take a look. Thanks!

**Comment by btea** [comment]
When editing code, the preview area will flash, and the fix PR https://github.com/vuejs/repl/pull/206 has been created.

**Comment by sxzz** [comment]
You now have write permission of the repo.

**Comment by btea** [comment]
Okay, got it.

**Pull request merged**
